export const HIDEASIDE = 'HIDEASIDE';
export const HIDEASIDEBAR = 'HIDEASIDEBAR';
export const SETBUILDINGID = 'SETBUILDINGID';
export const SETBUILDINGNAME = 'SETBUILDINGNAME';
export const SETBUILDINGTYPE = 'SETBUILDINGTYPE';
export const SETLINKBUILDINGTYPE = 'SETLINKBUILDINGTYPE';
export const SETCAMERACODE = 'SETCAMERACODE';
export const SETVIDEOSTATUS = 'SETVIDEOSTATUS';
